### ISSUE TITLE
Retina in Preprocessor

### ISSUE THREAD

**Issue by rmekdma** [berak/uniform-lbp#3]
Hi, I tested the preprocessor and found that retina gives an image which overlaps previous image.  Doing retina->clearBuffers(); before retina->run(procimg); solved this problem. Do you have the same problem in any case?

Thanks!

**Comment by berak** [comment]
oh, thanks for pointing this out, but i have not noticed that yet. how would i do so ?

do you have a smallish testcase i could try ?

**Comment by berak** [comment]
well, i did not notice before, but imho, you're  right about this,
there seems to be some 'interpolation' between the previous parvo img and the new one going on

```
        retina->getParvo(imgout); // just to check the issue
        imshow("ret1",imgout);     // prev. output
        imshow("inp",imgt);         // current input
        retina->run(imgt);            
        retina->getParvo(imgout); 
        imshow("ret2",imgout);      // new output.
```

![retina_bad](https://cloud.githubusercontent.com/assets/854416/9788322/3d8dbf9a-57c9-11e5-8d3b-fbe771e6ea4c.png)

and yes, retina->clearBuffers() does fix it, a ton of thanks for pointing it out !

(a real eye-opener, guess i have to reconsider the results for PCA_LDA due to this ;)

**Comment by rmekdma** [comment]
Good for you to solved it! I should have reported a sample code, but the time was late in my country  ;)
